### ISSUE TITLE
Browser redirects to 127.3.2.1:4242 unexpectedly

### ISSUE THREAD

**Issue by kaizushi** [oxen-io/session-pysogs#170]
I am trying to create a SOGS server using Debian Linux and the sogs-standalone setup. There is one detail about this server that is unusual, the server is a Tor hidden service. There is another server which hosts an nginx reverse proxy to this hidden server. This is something I have done many times and usually works quite well. The nginx reverse proxy does use SSL with LetsEncrypt. Despite this abnormal setup, it should work fine because sogs-standalone works using HTTP virtual hosts.

I do get a webpage through my nginx reverse proxy of the room list, but once a room is clicked my browser gets redirected to an address which does not work **http://127.3.2.1:4242/** and the browser complains it cannot reach it.

The problem is that the sogs standalone server does listen on port 80 and this is what I want. Regardless of that I want it to create links for HTTPS on port 443, because that is what my external _clearnet_ server uses, where it then redirects things to the Tor hidden service. Basically despite running on 80 I need it to give out HTTPS urls, or just use relative paths.

Beyond the [advice on installing the server](https://docs.oxen.io/products-built-on-oxen/session/guides/open-group-setup) and the help provided by the _sogs_ command I cannot really find any comprensive documentation, but if I just failed to Google it post a link for me below.

**Comment by jagerman** [comment]
The `sogs-proxied` package might well be a better fit for you; the sogs-standalone package is aimed at a one-shot quick install where you don't want to stick a front-end server in front of it.  When you do have a front-end, sogs-proxied is typically a better choice.  (See https://github.com/oxen-io/session-pysogs/blob/dev/install-debs.md)

You could go one step further than that and run it via uwsgi from a git checkout (more info on that at https://github.com/oxen-io/session-pysogs/blob/dev/install-uwsgi.md).  This is the setup we use for our official Session/Oxen open group, for instance.  (If you do go this way I recommend you stick to the `stable` branch rather than the default `dev` branch.)

**Comment by jagerman** [comment]
Actually it sounds like you might be using sogs-proxied already?  That `127.3.2.1:4242` comes in the default sogs-proxied configuration (https://github.com/oxen-io/session-pysogs/blob/dev/contrib/uwsgi-sogs-proxied.ini) and is what the default package configures it to listen on, expecting a reverse proxy in front of it to send things to it.

**Comment by kaizushi** [comment]
Ah, I was trying `sogs-proxied` but decided to undo all of that and use `sogs-standalone`

I believe what is actually happening to me is a cached redirect on my browser. I'm going to clear that cache and try again.

**Comment by kaizushi** [comment]
Yeah, nevermind, this was a stupid mistake on my part and I was right about the cached redirect. Thanks for taking interest, or I might not have noticed for a while!
