### ISSUE TITLE
Help: How to use this program to send a message to a group

### ISSUE THREAD

**Issue by liqsliu** [oxen-io/session-pysogs#53]
I want to use this program to create a group and push messages from other channels to the group at the same time. My code is here: https://github.com/liqsliu/session-pysogs/blob/7efa148dae9f9643a6da04e7e36989a6b0112ca5/sogs/mule.py#L99 
At present, I can't see the messages I send with it in the Android client, but I can see it in the web browser.

![IMG_20220205_201535_104~2](https://user-images.githubusercontent.com/5843584/152641737-77fa9c47-2931-4b2f-91bf-af795240e85f.jpg)

**Comment by jagerman** [comment]
> At present, I can't see the messages I send with it in the Android client, but I can see it in the web browser.

In order for Session to accept a message from there are two basic requirements:
- the message must be properly encoded in the appropriate protocol buffer encoding.  (It also pads messages, but that is optional).
- the message must have a signature created by the session id that posted it

The web viewer only does the first protobuf decoding, but doesn't verify signatures, so if it's showing there and not in actual Session it seems likely that the problem is with the signature.

**Comment by liqsliu** [comment]
How to generate a signature? Excuse me, is there any code for reference here?

**Comment by jagerman** [comment]
> How to generate a signature? Excuse me, is there any code for reference here?

Session message signatures are XEd25519 signatures, which is a custom signature algorithm inherited from Signal to produce Ed25519-compatible signatures using X25519 keypairs.  We don't currently have the ability to generate these in the pysogs codebase, so you'd need to extract code from Session or Signal to generate such a signature.
